# Generated by Django 3.1.2 on 2020-10-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='desc',
        ),
    ]
