# Generated by Django 3.1.2 on 2020-10-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201017_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
